# Generated by Django 3.2.9 on 2021-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_data_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
