# Generated by Django 3.2.9 on 2021-11-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211118_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='updated_at',
        ),
    ]
