# Generated by Django 3.2.9 on 2021-11-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20211118_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
