# Generated by Django 3.2.9 on 2021-11-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_data_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
