# Generated by Django 3.2.9 on 2021-11-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_user_data2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data2',
        ),
    ]
