# Generated by Django 3.2.9 on 2021-11-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_delete_user_data2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user_data',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
