# Generated by Django 3.2.9 on 2021-11-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20211118_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='password',
        ),
    ]
