# Generated by Django 3.2.9 on 2021-11-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_user_data_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='password',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
