# Generated by Django 3.2.9 on 2021-11-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_user_data_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='password',
        ),
    ]
